name: Update README with Issue Status

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows for manual triggering of the workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Ensure this is 14 or later

      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Update README
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          node update-readme.js

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README with issue status'
          git push
